"use server";
import { revalidatePath } from "next/cache";
import { requireWorkspace } from "@/lib/auth/server";
import { cancelSlot, createClass, createSlot, updateClass, updateSlot } from "@/lib/schedule";
export type ScheduleState = { error?: string; success?: string; fieldErrors?: Partial<Record<"classId" | "localDate" | "startTime" | "endTime" | "capacity" | "trainerUid", string>> };
const message = (error: unknown) => { const code = error instanceof Error ? error.message : "Unable to save the schedule."; return ({ FORBIDDEN_SCHEDULE: "You do not have permission to manage this schedule.", TRAINER_NOT_ELIGIBLE: "Choose an active trainer from this studio.", TRAINER_SLOT_OVERLAP: "This trainer already has an overlapping slot.", NONEXISTENT_STUDIO_TIME: "That local time does not exist in the studio timezone.", SLOT_END_MUST_FOLLOW_START: "End time must be after start time.", SLOT_START_MUST_BE_FUTURE: "Choose a start time that is still in the future.", CLASS_UNAVAILABLE: "Choose an active class.", CAPACITY_BELOW_BOOKINGS: "Capacity cannot be lower than the confirmed booking count.", SLOT_HAS_BOOKINGS: "This slot has confirmed bookings. Only capacity may be changed, and it cannot be lower than the booked count.", SLOT_NOT_EDITABLE: "Cancelled or completed slots cannot be edited.", SLOT_NOT_FOUND: "This slot no longer exists." } as Record<string, string>)[code] ?? code; };
function slotErrorState(error: unknown): ScheduleState { const code = error instanceof Error ? error.message : ""; const field = ({ CLASS_UNAVAILABLE: "classId", TRAINER_NOT_ELIGIBLE: "trainerUid", TRAINER_SLOT_OVERLAP: "trainerUid", NONEXISTENT_STUDIO_TIME: "startTime", SLOT_END_MUST_FOLLOW_START: "endTime" } as Record<string, "classId" | "localDate" | "startTime" | "endTime" | "capacity" | "trainerUid">)[code]; return field ? { fieldErrors: { [field]: message(error) } } : { error: message(error) }; }
export async function createClassAction(_: ScheduleState, form: FormData): Promise<ScheduleState> { try { const p = await requireWorkspace("/studio"); await createClass(p, Object.fromEntries(form)); revalidatePath("/studio/schedule"); return { success: "Class created." }; } catch (e) { return { error: message(e) }; } }
export async function createSlotAction(_: ScheduleState, form: FormData): Promise<ScheduleState> { try { const p = await requireWorkspace("/studio"); await createSlot(p, Object.fromEntries(form)); revalidatePath("/studio/schedule"); return { success: "One-off slot created." }; } catch (e) { return slotErrorState(e); } }
export async function updateClassAction(_: ScheduleState, form: FormData): Promise<ScheduleState> { try { const p = await requireWorkspace("/studio"); await updateClass(p, Object.fromEntries(form)); revalidatePath("/studio/schedule"); return { success: "Class saved." }; } catch (e) { return { error: message(e) }; } }
export async function updateSlotAction(_: ScheduleState, form: FormData): Promise<ScheduleState> { try { const p = await requireWorkspace("/studio"); await updateSlot(p, Object.fromEntries(form)); revalidatePath("/studio/schedule"); return { success: "Slot saved." }; } catch (e) { return { error: message(e) }; } }
export async function cancelSlotAction(_: ScheduleState, form: FormData): Promise<ScheduleState> { try { const p = await requireWorkspace("/studio"); await cancelSlot(p, Object.fromEntries(form)); revalidatePath("/studio/schedule"); return { success: "Slot cancelled." }; } catch (e) { return { error: message(e) }; } }
