"use client";

import { useActionState, useState } from "react";
import { acknowledgeIncidentReviewAction, reverseIncidentAction, saveIncidentPolicyAction, waiveIncidentAction, type IncidentActionState } from "@/app/studio/incidents/actions";
import styles from "./incident-ui.module.css";

type Incident = { id: string; customerName: string; type: string; status: string; sourceTimestamp: string; reviewRequiredAtCreation: boolean; currentActiveIncidentCount: number; currentReviewRequired: boolean; reviewed: boolean };
const initial: IncidentActionState = {};
export function IncidentManager({ incidents, policy, owner }: { incidents: Incident[]; policy: { version: number; rollingDays: number; threshold: number; status: "active" | "inactive" }; owner: boolean }) {
  const [policyState, policyAction, policyPending] = useActionState(saveIncidentPolicyAction, initial);
  const [waiveState, waiveAction, waivePending] = useActionState(waiveIncidentAction, initial);
  const [reverseState, reverseAction, reversePending] = useActionState(reverseIncidentAction, initial);
  const [reviewState, reviewAction, reviewPending] = useActionState(acknowledgeIncidentReviewAction, initial);
  const [policyOperation] = useState(() => crypto.randomUUID());
  const [query, setQuery] = useState("");
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);
  const visibleIncidents = incidents.filter((incident) => !query.trim() || incident.customerName.toLowerCase().includes(query.trim().toLowerCase()) || incident.type.includes(query.trim().toLowerCase()));
  const activeCount = incidents.filter((incident) => incident.status === "active").length;
  return <main className={styles.page}><header className={styles.header}><div><p className={styles.kicker}>OWNER INCIDENT POLICY</p><h1>Review patterns, keep context.</h1><p>{activeCount} active incidents in {policy.rollingDays} days flag an Owner review. It does not restrict bookings or change credits.</p></div><div className={styles.headerAside}><a className={styles.back} href="/studio">← Studio dashboard</a><div className={styles.headerImage} aria-hidden="true" /></div></header>
    <div className={styles.topGrid}><section className={styles.panel}><div className={styles.panelHeading}><span>◈</span><div><p className={styles.kicker}>CURRENT POLICY</p><h2>Owner review threshold</h2><small>Configure when a client is flagged for Owner review.</small></div></div><p className={styles.note}>Version {policy.version} · {policy.threshold} active incidents / {policy.rollingDays} rolling days · {policy.status}</p>{owner ? <form action={policyAction} className={styles.form}><input type="hidden" name="operationId" value={policyOperation} /><label>Policy state<select name="status" defaultValue={policy.status} disabled={policyPending}><option value="active">Active</option><option value="inactive">Inactive</option></select></label>{policyState.error && <p className={styles.error} role="alert">{policyState.error}</p>}{policyState.success && <p className={styles.success} role="status">{policyState.success}</p>}<button disabled={policyPending}>{policyPending ? "Saving…" : "Save policy"}</button></form> : <p className={styles.empty}>Only the studio owner can configure policy.</p>}</section>
      <section className={styles.panel}><div className={styles.panelHeading}><span>▤</span><div><p className={styles.kicker}>INCIDENT HISTORY</p><h2>Factual source records</h2><small>View all recorded incidents, including late cancellations and no-shows.</small></div></div><div className={styles.historyTools}><label><span>⌕</span><input type="search" placeholder="Search by client name or email…" aria-label="Search incidents" value={query} onChange={(event) => setQuery(event.target.value)} /></label><button type="button">◫ Last {policy.rollingDays} days</button></div><div className={styles.filters}><button type="button" className={styles.activeFilter}>All types</button><button type="button">Late cancellation</button><button type="button">No-show</button><button type="button">Other</button></div></section></div>
    <section className={styles.records}><div className={styles.recordsHeading}><div className={styles.panelHeading}><span>♧</span><div><p className={styles.kicker}>RECORDED INCIDENTS</p><h2>Recent incident records</h2><small>These records are used to identify patterns and flag clients for Owner review.</small></div></div><label><span>⌕</span><input type="search" placeholder="Search by name or email…" aria-label="Search recorded incidents" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div>{[waiveState, reverseState, reviewState].map((state, index) => <div key={index}>{state.error && <p className={styles.error} role="alert">{state.error}</p>}{state.success && <p className={styles.success} role="status">{state.success}</p>}</div>)}<div className={styles.tableHead} aria-hidden="true"><span>#</span><span>Client</span><span>Type</span><span>Recorded on</span><span>Status</span><span>Review</span><span>Actions</span></div><div className={styles.rows}>{visibleIncidents.map((incident, index) => { const timestamp = new Date(incident.sourceTimestamp); return <article className={styles.row} key={incident.id}><span>{index + 1}</span><span className={styles.client}><i>{incident.customerName.charAt(0).toUpperCase()}</i>{incident.customerName}</span><span><em className={incident.type === "no-show" ? styles.noShow : styles.late}>{incident.type.replaceAll("-", " ")}</em></span><time>{Number.isNaN(timestamp.valueOf()) ? "—" : timestamp.toLocaleString()}</time><span className={styles.status}>{incident.status}</span><span>{incident.currentReviewRequired ? "Review required" : incident.reviewed ? "Reviewed" : "—"}</span><div><button type="button" onClick={() => setSelectedIncident(incident)}>View</button><button type="button" aria-label={`More actions for ${incident.customerName}`}>⋮</button></div></article>; })}</div>{incidents.length === 0 ? <p className={styles.empty}>No qualifying late cancellations or no-shows have been recorded.</p> : visibleIncidents.length === 0 ? <p className={styles.empty}>No incident records match that search.</p> : null}</section>
    {selectedIncident && <div className={styles.backdrop} role="presentation" onMouseDown={() => setSelectedIncident(null)}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="incident-dialog-title" onMouseDown={(event) => event.stopPropagation()}><button type="button" className={styles.close} onClick={() => setSelectedIncident(null)} aria-label="Close incident details">×</button><p className={styles.kicker}>INCIDENT RECORD</p><h2 id="incident-dialog-title">{selectedIncident.customerName}</h2><p className={styles.modalMeta}>{selectedIncident.type.replaceAll("-", " ")} · {new Date(selectedIncident.sourceTimestamp).toLocaleString()}</p><p className={styles.note}>{selectedIncident.currentActiveIncidentCount} active incidents in the current {policy.rollingDays}-day window{selectedIncident.currentReviewRequired ? " · owner review required" : ""}{selectedIncident.reviewed ? " · review acknowledged" : ""}</p>{owner && selectedIncident.status === "active" && <div className={styles.modalActions}><form action={waiveAction}><input type="hidden" name="incidentId" value={selectedIncident.id} /><input type="hidden" name="operationId" value={crypto.randomUUID()} /><label>Waiver reason<input name="reason" minLength={2} maxLength={300} required disabled={waivePending} /></label><button disabled={waivePending}>{waivePending ? "Saving…" : "Waive incident"}</button></form><form action={reviewAction}><input type="hidden" name="incidentId" value={selectedIncident.id} /><input type="hidden" name="operationId" value={crypto.randomUUID()} /><button className={styles.secondary} disabled={reviewPending || selectedIncident.reviewed}>{selectedIncident.reviewed ? "Review acknowledged" : reviewPending ? "Saving…" : "Acknowledge review"}</button></form>{selectedIncident.type === "no-show" && <form action={reverseAction}><input type="hidden" name="incidentId" value={selectedIncident.id} /><input type="hidden" name="operationId" value={crypto.randomUUID()} /><label>Factual reversal reason<input name="reason" minLength={2} maxLength={300} required disabled={reversePending} /></label><button className={styles.secondary} disabled={reversePending}>{reversePending ? "Saving…" : "Reverse after attendance correction"}</button></form>}</div>}</section></div>}
  </main>;
}
