"use client";

import Link from "next/link";
import { FormEvent, useActionState, useEffect, useState } from "react";
import { createUserWithEmailAndPassword } from "firebase/auth";
import { useRouter } from "next/navigation";
import { acceptInvitationAction, type TeamActionState } from "@/app/studio/team/actions";
import { firebaseClientConfigured, getClientAuth } from "@/lib/firebase/client";
import styles from "./sprint-one.module.css";

const initial: TeamActionState = {};
export function InvitationAcceptance({ invitationId, token, email, displayName, signedInEmail }: { invitationId: string; token: string; email: string; displayName: string; signedInEmail: string | null }) {
  const router = useRouter(); const [state, action, pending] = useActionState(acceptInvitationAction, initial); const [setupError, setSetupError] = useState(""); const [setupPending, setSetupPending] = useState(false);
  const continuePath = `/invite/${invitationId}?token=${encodeURIComponent(token)}`; const matched = signedInEmail?.toLowerCase() === email.toLowerCase();
  useEffect(() => { if (state.success) router.replace("/entry"); }, [router, state.success]);
  async function createAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSetupError(""); setSetupPending(true); const form = new FormData(event.currentTarget); const password = String(form.get("password") ?? ""); const confirmation = String(form.get("confirmation") ?? ""); if (password !== confirmation) { setSetupError("Passwords do not match."); setSetupPending(false); return; } try { const credential = await createUserWithEmailAndPassword(getClientAuth(), email, password); const response = await fetch("/api/auth/session", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idToken: await credential.user.getIdToken() }) }); if (!response.ok) throw new Error("We could not establish your secure session."); router.refresh(); } catch (error) { setSetupError(error instanceof Error && error.message.includes("email-already-in-use") ? "An account already exists for this email. Sign in to accept the invitation." : error instanceof Error ? error.message : "Unable to create your account."); } finally { setSetupPending(false); } }
  return <main className={styles.simplePage}><section className={styles.simpleCard}><p className={styles.kicker}>STUDIO INVITATION</p><h1>{displayName ? `Welcome, ${displayName}` : "You’re invited to StudioFlow"}</h1><p className={styles.muted}>This invitation is for <b>{email}</b>. It becomes studio access only after you accept it.</p>{!signedInEmail ? <><p className={styles.muted}>Already have a Firebase account for this email? Sign in first—your password will not be changed.</p><Link className={styles.textLink} href={`/?continue=${encodeURIComponent(continuePath)}`}>Sign in to accept</Link><form onSubmit={createAccount} className={styles.form}><h2>New to StudioFlow?</h2><p className={styles.muted}>Create your password to continue. StudioFlow will not email this link for you.</p><label>New password<input name="password" type="password" autoComplete="new-password" minLength={8} required disabled={!firebaseClientConfigured() || setupPending} /></label><label>Confirm password<input name="confirmation" type="password" autoComplete="new-password" minLength={8} required disabled={!firebaseClientConfigured() || setupPending} /></label>{setupError && <p className={styles.formError} role="alert">{setupError}</p>}<button className={styles.primary} disabled={!firebaseClientConfigured() || setupPending}>{setupPending ? "Creating account…" : "Create account"}</button></form></> : !matched ? <><p className={styles.formError} role="alert">This invitation belongs to another email address. Sign in with {email} to continue.</p><Link className={styles.textLink} href="/">Return to sign in</Link></> : <form action={action} className={styles.form}><input type="hidden" name="invitationId" value={invitationId} /><input type="hidden" name="token" value={token} />{state.error && <p className={styles.formError} role="alert">{state.error}</p>}{state.success && <p className={styles.success} role="status">{state.success}</p>}<button className={styles.primary} disabled={pending}>{pending ? "Activating access…" : "Accept invitation"}</button></form>}</section></main>;
}
