"use client";

import Image from "next/image";
import { useActionState, useEffect, useState } from "react";
import Swal from "sweetalert2";
import { cancelSlotAction, createClassAction, createSlotAction, updateClassAction, updateSlotAction, type ScheduleState } from "@/app/studio/schedule-actions";
import studioImage from "@/app/assets/pilates-studio.png";
import styles from "./schedule.module.css";
import scheduleStyles from "./schedule-ui.module.css";
import readableStyles from "./schedule-readable.module.css";

type ClassItem = { id: string; name: string; description: string; durationMinutes: number; status: string };
type Trainer = { uid: string; name: string };
type Slot = { id: string; className: string; trainerUid: string; trainerName: string; localDate: string; startTime: string; endTime: string; capacity: number; confirmedBookingCount: number; status: string; isPast: boolean };
const initial: ScheduleState = {};

function SlotEditor({ slot, trainers, action, cancelAction, pending, cancelPending, onClose }: { slot: Slot; trainers: Trainer[]; action: (payload: FormData) => void; cancelAction: (payload: FormData) => void; pending: boolean; cancelPending: boolean; onClose: () => void }) {
  const [operationId] = useState(() => crypto.randomUUID());
  return <div className={scheduleStyles.modalBackdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className={scheduleStyles.slotModal} role="dialog" aria-modal="true" aria-labelledby="slot-editor-title"><div className={scheduleStyles.modalHeader}><div><p>EDIT SCHEDULED SLOT</p><h2 id="slot-editor-title">{slot.className}</h2><span>{slot.localDate} · {slot.startTime}–{slot.endTime}</span></div><button type="button" onClick={onClose} aria-label="Close edit slot dialog">×</button></div><form action={action} className={`${styles.form} ${scheduleStyles.compactEditForm}`}><input type="hidden" name="slotId" value={slot.id} /><input type="hidden" name="operationId" value={operationId} /><div className={styles.two}><label>Date<input name="localDate" type="date" defaultValue={slot.localDate} required disabled={pending} /></label><label>Capacity<input name="capacity" type="number" min={slot.confirmedBookingCount} max="100" defaultValue={slot.capacity} required disabled={pending} /></label></div><div className={styles.two}><label>Start time<input name="startTime" type="time" defaultValue={slot.startTime} required disabled={pending} /></label><label>End time<input name="endTime" type="time" defaultValue={slot.endTime} required disabled={pending} /></label></div><label>Trainer<select name="trainerUid" defaultValue={slot.trainerUid} disabled={pending}>{trainers.map((trainer) => <option key={trainer.uid} value={trainer.uid}>{trainer.name}</option>)}</select></label><label>Status<select name="status" defaultValue={slot.status} disabled={pending}><option value="draft">Draft</option><option value="published">Published</option></select></label><button disabled={pending}>{pending ? "Saving…" : "Save changes"}</button></form><form action={cancelAction} className={scheduleStyles.cancelForm}><input type="hidden" name="slotId" value={slot.id} /><button type="submit" disabled={cancelPending || slot.confirmedBookingCount > 0}>{cancelPending ? "Cancelling…" : "Cancel slot"}</button>{slot.confirmedBookingCount > 0 && <span>Bookings prevent cancellation.</span>}</form></section></div>;
}

function ClassEditor({ item, action, pending, onClose }: { item: ClassItem; action: (payload: FormData) => void; pending: boolean; onClose: () => void }) {
  return <div className={scheduleStyles.modalBackdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className={scheduleStyles.classModal} role="dialog" aria-modal="true" aria-labelledby="class-editor-title"><div className={scheduleStyles.modalHeader}><div><p>EDIT REUSABLE CLASS</p><h2 id="class-editor-title">{item.name}</h2><span>Changes apply only to future slots.</span></div><button type="button" onClick={onClose} aria-label="Close edit class dialog">×</button></div><form action={action} className={`${styles.form} ${scheduleStyles.compactEditForm}`}><input type="hidden" name="classId" value={item.id} /><label>Class name<input name="name" defaultValue={item.name} minLength={2} maxLength={80} required disabled={pending} /></label><label>Description<textarea name="description" defaultValue={item.description} maxLength={400} disabled={pending} /></label><div className={styles.two}><label>Duration<input name="durationMinutes" type="number" min="15" max="240" defaultValue={item.durationMinutes} required disabled={pending} /></label><label>Status<select name="status" defaultValue={item.status} disabled={pending}><option value="active">Active</option><option value="draft">Draft</option><option value="retired">Retired</option></select></label></div><p className={styles.note}>Retiring prevents new slots. Existing scheduled slots keep their history.</p><button disabled={pending}>{pending ? "Saving…" : "Save class"}</button></form></section></div>;
}

export function ScheduleManager({ timezone, classes, trainers, slots }: { timezone: string; classes: ClassItem[]; trainers: Trainer[]; slots: Slot[] }) {
  const [classState, classAction, classPending] = useActionState(createClassAction, initial);
  const [slotState, slotAction, slotPending] = useActionState(createSlotAction, initial);
  const [editState, editAction, editPending] = useActionState(updateSlotAction, initial);
  const [classEditState, classEditAction, classEditPending] = useActionState(updateClassAction, initial);
  const [cancelState, cancelAction, cancelPending] = useActionState(cancelSlotAction, initial);
  const [selectedSlot, setSelectedSlot] = useState<Slot | null>(null);
  const [selectedClass, setSelectedClass] = useState<ClassItem | null>(null);
  const [classOperation] = useState(() => crypto.randomUUID());
  const [slotOperation] = useState(() => crypto.randomUUID());
  const activeClasses = classes.filter((item) => item.status === "active");
  const [slotDraft, setSlotDraft] = useState({ classId: activeClasses[0]?.id ?? "", localDate: "", startTime: "", endTime: "", capacity: "8", trainerUid: trainers[0]?.uid ?? "", status: "draft" });
  const updateSlotDraft = (field: keyof typeof slotDraft, value: string) => setSlotDraft((current) => ({ ...current, [field]: value }));
  useEffect(() => { if (classState.success) void Swal.fire({ icon: "success", title: "Class created", text: classState.success, confirmButtonText: "Done" }); }, [classState.success]);
  useEffect(() => { if (editState.success) { setSelectedSlot(null); void Swal.fire({ icon: "success", title: "Slot updated", text: editState.success, confirmButtonText: "Done" }); } }, [editState.success]);
  useEffect(() => { if (editState.error) void Swal.fire({ icon: "error", title: "Slot not updated", text: editState.error, confirmButtonText: "Review slot" }); }, [editState.error]);

  return <main className={`${styles.page} ${styles.studioPolish} ${scheduleStyles.scheduleUi} ${readableStyles.scheduleReadable}`}>
    <header className={`${styles.header} ${scheduleStyles.scheduleHeader}`}>
      <div><p className={styles.kicker}>STUDIO SCHEDULE</p><h1>Build a calm, reliable week.</h1><p>One-off slots only · studio time: <b>{timezone}</b></p></div>
      <div className={scheduleStyles.headerActions}><a className={styles.back} href="/studio">← Studio dashboard</a><div className={scheduleStyles.heroImage}><Image src={studioImage} alt="Pilates studio" fill sizes="300px" priority /></div></div>
    </header>

    <div className={`${styles.grid} ${scheduleStyles.scheduleGrid}`}>
      <section className={`${styles.panel} ${scheduleStyles.schedulePanel}`}>
        <div className={scheduleStyles.panelHeading}><div><p className={styles.kicker}>CLASS LIBRARY</p><h2>Reusable class details</h2></div><details className={scheduleStyles.addClass}><summary>＋ Add class</summary><form action={classAction} className={styles.form}><input type="hidden" name="operationId" value={classOperation} /><label>Class name<input name="name" required minLength={2} placeholder="Reformer foundations" disabled={classPending} /></label><label>Description <textarea name="description" maxLength={400} placeholder="A considered introduction to reformer work." disabled={classPending} /></label><div className={styles.two}><label>Duration<input name="durationMinutes" type="number" min="15" max="240" defaultValue="50" required disabled={classPending} /></label><label>Status<select name="status" defaultValue="active" disabled={classPending}><option value="active">Active</option><option value="draft">Draft</option></select></label></div>{classState.error && <p className={styles.error} role="alert">{classState.error}</p>}{classState.success && <p className={styles.success} role="status">{classState.success}</p>}<button disabled={classPending}>{classPending ? "Creating…" : "Create class"}</button></form></details></div>
        <label className={scheduleStyles.classSearch}><span>⌕</span><input type="search" placeholder="Search classes…" aria-label="Search classes" /></label>
        {classEditState.error && <p className={styles.error} role="alert">{classEditState.error}</p>}{classEditState.success && <p className={styles.success} role="status">{classEditState.success}</p>}<div className={`${styles.list} ${scheduleStyles.classList}`}>{classes.length ? classes.map((item) => <article key={item.id} className={scheduleStyles.classRow}><div className={scheduleStyles.classThumbnail}><Image src={studioImage} alt="" fill sizes="70px" /></div><div><b>{item.name}</b><span>◷ &nbsp;{item.durationMinutes} min <em>{item.status}</em></span><p>Reusable studio class</p></div><button type="button" className={scheduleStyles.moreButton} onClick={() => setSelectedClass(item)} aria-label={`Edit ${item.name}`}>⋮</button></article>) : <p className={styles.empty}>No classes yet. Create the reusable offering first.</p>}</div>
      </section>

      <section className={`${styles.panel} ${scheduleStyles.schedulePanel} ${scheduleStyles.slotPanel}`}>
        <div className={scheduleStyles.panelHeading}><div><p className={styles.kicker}>ONE-OFF SLOT</p><h2>Schedule a concrete class</h2></div></div>
        {!activeClasses.length ? <p className={styles.empty}>Create an active class before scheduling a slot.</p> : !trainers.length ? <p className={styles.empty}>No active trainer memberships are available. A published slot requires exactly one active trainer from this studio.</p> : <form action={slotAction} className={`${styles.form} ${scheduleStyles.slotForm}`}>
          <input type="hidden" name="operationId" value={slotOperation} />
          <label>Class<select name="classId" required disabled={slotPending} value={slotDraft.classId} onChange={(event) => updateSlotDraft("classId", event.target.value)} aria-invalid={Boolean(slotState.fieldErrors?.classId)} aria-describedby={slotState.fieldErrors?.classId ? "slot-class-error" : undefined}>{activeClasses.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.durationMinutes} min</option>)}</select>{slotState.fieldErrors?.classId && <span id="slot-class-error" className={styles.fieldError} role="alert">{slotState.fieldErrors.classId}</span>}</label>
          <div className={scheduleStyles.slotTimeGrid}><label>Date<input name="localDate" type="date" required disabled={slotPending} value={slotDraft.localDate} onChange={(event) => updateSlotDraft("localDate", event.target.value)} aria-invalid={Boolean(slotState.fieldErrors?.localDate)} />{slotState.fieldErrors?.localDate && <span className={styles.fieldError} role="alert">{slotState.fieldErrors.localDate}</span>}</label><label>Start time<input name="startTime" type="time" required disabled={slotPending} value={slotDraft.startTime} onChange={(event) => updateSlotDraft("startTime", event.target.value)} aria-invalid={Boolean(slotState.fieldErrors?.startTime)} />{slotState.fieldErrors?.startTime && <span className={styles.fieldError} role="alert">{slotState.fieldErrors.startTime}</span>}</label><label>End time<input name="endTime" type="time" required disabled={slotPending} value={slotDraft.endTime} onChange={(event) => updateSlotDraft("endTime", event.target.value)} aria-invalid={Boolean(slotState.fieldErrors?.endTime)} />{slotState.fieldErrors?.endTime && <span className={styles.fieldError} role="alert">{slotState.fieldErrors.endTime}</span>}</label></div>
          <div className={styles.two}><label>Capacity<input name="capacity" type="number" min="1" max="100" required disabled={slotPending} value={slotDraft.capacity} onChange={(event) => updateSlotDraft("capacity", event.target.value)} aria-invalid={Boolean(slotState.fieldErrors?.capacity)} />{slotState.fieldErrors?.capacity && <span className={styles.fieldError} role="alert">{slotState.fieldErrors.capacity}</span>}</label><label>Trainer<select name="trainerUid" required disabled={slotPending} value={slotDraft.trainerUid} onChange={(event) => updateSlotDraft("trainerUid", event.target.value)} aria-invalid={Boolean(slotState.fieldErrors?.trainerUid)}>{trainers.map((trainer) => <option key={trainer.uid} value={trainer.uid}>{trainer.name}</option>)}</select>{slotState.fieldErrors?.trainerUid && <span className={styles.fieldError} role="alert">{slotState.fieldErrors.trainerUid}</span>}</label></div>
          <label>Status<select name="status" disabled={slotPending} value={slotDraft.status} onChange={(event) => updateSlotDraft("status", event.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><p className={styles.note}>ⓘ Times are interpreted in {timezone}. Same-trainer overlaps are not permitted.</p>{slotState.error && <p className={styles.error} role="alert">{slotState.error}</p>}{slotState.success && <p className={styles.success} role="status">{slotState.success}</p>}<button disabled={slotPending}>{slotPending ? "Scheduling…" : "Create one-off slot"}</button>
        </form>}
      </section>
    </div>

    <section className={`${styles.panel} ${scheduleStyles.upcomingPanel}`}><div className={scheduleStyles.upcomingHeading}><div><p className={styles.kicker}>UPCOMING SLOTS</p><h2>Today and upcoming</h2></div><span>◷ &nbsp;{slots.length} slots</span></div><p className={scheduleStyles.scheduleNotice}>Edit a future slot before customers book. Once bookings exist, only capacity can be safely increased.</p>{editState.error && <p className={styles.error} role="alert">{editState.error}</p>}{editState.success && <p className={styles.success} role="status">{editState.success}</p>}{cancelState.error && <p className={styles.error} role="alert">{cancelState.error}</p>}{cancelState.success && <p className={styles.success} role="status">{cancelState.success}</p>}{slots.length ? <div className={scheduleStyles.slotTable}><div className={scheduleStyles.slotTableHead} aria-hidden="true"><span>Time</span><span>Class</span><span>Bookings</span><span>Status</span><span>Actions</span></div>{slots.map((slot) => { const remaining = Math.max(0, slot.capacity - slot.confirmedBookingCount); const status = slot.isPast ? "Past" : slot.status === "published" && remaining === 0 ? "Full" : slot.status; const editable = !slot.isPast && slot.status !== "cancelled" && slot.status !== "completed"; return <article key={slot.id} className={scheduleStyles.slotRow}><span className={scheduleStyles.slotTime}>{slot.startTime} – {slot.endTime}<small>{slot.localDate}</small></span><div className={scheduleStyles.slotClass}><div className={scheduleStyles.slotThumbnail}><Image src={studioImage} alt="" fill sizes="46px" /></div><span><b>{slot.className}</b><small>{slot.trainerName}</small></span></div><span>{slot.confirmedBookingCount} / {slot.capacity} booked<small>{remaining} available</small></span><em className={scheduleStyles.slotBadge}>{status}</em><div className={scheduleStyles.slotActions}>{(slot.status === "published" || slot.status === "completed") && <a className={styles.back} href={`/studio/attendance/${slot.id}`}>Roster &amp; attendance</a>}{editable && <button type="button" className={scheduleStyles.slotEditButton} onClick={() => setSelectedSlot(slot)}>Edit</button>}<button type="button" className={scheduleStyles.moreButton} onClick={() => editable && setSelectedSlot(slot)} aria-label={`Edit ${slot.className}`} disabled={!editable}>⋮</button></div></article>; })}</div> : <p className={styles.empty}>No concrete slots have been created. Draft slots stay internal until published.</p>}</section>{selectedSlot && <SlotEditor slot={selectedSlot} trainers={trainers} action={editAction} cancelAction={cancelAction} pending={editPending} cancelPending={cancelPending} onClose={() => setSelectedSlot(null)} />}{selectedClass && <ClassEditor item={selectedClass} action={classEditAction} pending={classEditPending} onClose={() => setSelectedClass(null)} />}
  </main>;
}
