"use client";

import { useActionState, useEffect, useRef, useState, type ReactNode } from "react";
import Swal from "sweetalert2";
import { requestOwnPauseAction, requestOwnResumeAction, type CustomerSubscriptionActionState } from "@/app/customer/subscription-actions";
import styles from "./booking.module.css";

const initial: CustomerSubscriptionActionState = {};

function ConfirmationDialog({ title, message, cancelLabel, confirmLabel, pending, pendingLabel = "Saving…", onClose, children }: { title: string; message: string; cancelLabel: string; confirmLabel: string; pending: boolean; pendingLabel?: string; onClose: () => void; children?: ReactNode }) {
  const dialog = useRef<HTMLElement>(null);
  useEffect(() => { const node = dialog.current; node?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) onClose(); }; window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [onClose, pending]);
  return <div className={styles.confirmationBackdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !pending) onClose(); }}><section ref={dialog} className={styles.confirmationDialog} role="dialog" aria-modal="true" aria-labelledby="subscription-confirmation-title" tabIndex={-1}><p className={styles.kicker}>CONFIRM ACTION</p><h2 id="subscription-confirmation-title">{title}</h2><p>{message}</p>{children}<div><button type="button" className={styles.secondaryButton} onClick={onClose} disabled={pending}>{cancelLabel}</button><button type="submit" disabled={pending}>{pending ? pendingLabel : confirmLabel}</button></div></section></div>;
}

export function SubscriptionPauseControl({ subscriptionId, status, durationMonths, pauseDaysUsed, pauseAllowanceDays, pauseEndsAt }: { subscriptionId: string; status: string; durationMonths: number | null; pauseDaysUsed: number; pauseAllowanceDays: number; pauseEndsAt: string | null }) {
  const [pauseState, pauseAction, pausing] = useActionState(requestOwnPauseAction, initial);
  const [resumeState, resumeAction, resuming] = useActionState(requestOwnResumeAction, initial);
  const [confirmingPause, setConfirmingPause] = useState(false); const [confirmingResume, setConfirmingResume] = useState(false);
  useEffect(() => { if (pauseState.success) void Swal.fire({ icon: "success", title: "Pause applied", text: pauseState.success, confirmButtonText: "Done", customClass: { popup: styles.swalPopup, confirmButton: styles.swalConfirm } }); else if (pauseState.error) void Swal.fire({ icon: "error", title: "Couldn’t pause membership", text: pauseState.error, confirmButtonText: "Close", customClass: { popup: styles.swalPopup, confirmButton: styles.swalConfirm } }); }, [pauseState.error, pauseState.success]);
  useEffect(() => { if (resumeState.success) void Swal.fire({ icon: "success", title: "Subscription resumed", text: resumeState.success, confirmButtonText: "Done", customClass: { popup: styles.swalPopup, confirmButton: styles.swalConfirm } }); else if (resumeState.error) void Swal.fire({ icon: "error", title: "Couldn’t resume membership", text: resumeState.error, confirmButtonText: "Close", customClass: { popup: styles.swalPopup, confirmButton: styles.swalConfirm } }); }, [resumeState.error, resumeState.success]);
  if (!durationMonths) return <p className={styles.note}>This fixed-day plan is not eligible for pause.</p>;
  if (status === "paused") return <form action={resumeAction} className={`${styles.form} ${styles.pauseControl}`}><input type="hidden" name="subscriptionId" value={subscriptionId} /><input type="hidden" name="operationId" defaultValue={crypto.randomUUID()} /><p className={styles.note}>Your subscription is paused{pauseEndsAt ? ` until ${new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(pauseEndsAt))}` : ""}. Existing bookings and reserved credits remain unchanged.</p><button type="button" onClick={() => setConfirmingResume(true)} disabled={resuming || Boolean(resumeState.success)}>Resume subscription <span aria-hidden="true">›</span></button>{confirmingResume && <ConfirmationDialog title="Resume your subscription?" message="You’ll be able to book classes again. Only the calendar days already paused will count against your allowance." cancelLabel="Keep paused" confirmLabel="Confirm resume" pending={resuming} pendingLabel="Resuming…" onClose={() => setConfirmingResume(false)} />}</form>;
  if (status !== "active") return null;
  const remaining = pauseAllowanceDays - pauseDaysUsed;
  if (remaining < 1) return <p className={styles.note}>Your {pauseAllowanceDays}-day pause allowance has been used.</p>;
  return <form action={pauseAction} className={`${styles.form} ${styles.pauseControl}`}><input type="hidden" name="subscriptionId" value={subscriptionId} /><input type="hidden" name="operationId" defaultValue={crypto.randomUUID()} /><p className={styles.note}>Pause begins now. It does not change your credits or existing bookings.</p><button type="button" onClick={() => setConfirmingPause(true)} disabled={pausing || Boolean(pauseState.success)}><span aria-hidden="true">⏸</span>Pause subscription <b aria-hidden="true">›</b></button>{confirmingPause && <ConfirmationDialog title="Pause your subscription?" message="New bookings will be unavailable while paused. Existing bookings and reserved credits will stay as they are." cancelLabel="Go back" confirmLabel="Confirm pause" pending={pausing} onClose={() => setConfirmingPause(false)}><label className={styles.pauseModalDays}><span>Number of pause days</span><input name="pauseDays" type="number" min="1" max={remaining} required disabled={pausing} autoFocus /><small>Up to {remaining} day{remaining === 1 ? "" : "s"} remaining</small></label></ConfirmationDialog>}</form>;
}
