import "server-only";

import { randomUUID } from "node:crypto";
import { FieldValue } from "firebase-admin/firestore";
import { getAdminDb } from "@/lib/firebase/admin";
import { brandPaletteSchema } from "@/lib/validation";

export type BrandPalette = { id: string; name: string; background: string; surface: string; primary: string; accent: string };

function luminance(hex: string) { const rgb = [1, 3, 5].map((index) => Number.parseInt(hex.slice(index, index + 2), 16) / 255).map((value) => value <= .03928 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4); return .2126 * rgb[0] + .7152 * rgb[1] + .0722 * rgb[2]; }
function contrast(left: string, right: string) { const [a, b] = [luminance(left), luminance(right)].sort((x, y) => y - x); return (a + .05) / (b + .05); }
function readableOn(background: string) { return contrast(background, "#FFFFFF") >= contrast(background, "#18332E") ? "#FFFFFF" : "#18332E"; }

export function paletteVariables(palette: BrandPalette) { const text = readableOn(palette.background); const buttonText = readableOn(palette.primary); if (contrast(text, palette.background) < 4.5 || contrast(buttonText, palette.primary) < 4.5) throw new Error("PALETTE_CONTRAST_FAILED"); return { "--color-background": palette.background, "--color-surface": palette.surface, "--color-surface-secondary": palette.accent, "--color-primary": palette.primary, "--color-primary-hover": palette.primary, "--color-secondary": palette.accent, "--color-accent": palette.accent, "--color-text": text, "--color-text-muted": text, "--color-border": palette.accent, "--color-input-background": palette.surface, "--color-input-border": palette.accent, "--color-button-background": palette.primary, "--color-button-text": buttonText, "--color-button-hover": palette.primary, "--color-nav-background": palette.surface, "--color-nav-text": text, "--color-nav-active": palette.primary, "--color-nav-active-background": palette.accent, "--color-focus": palette.accent }; }
/** Platform palette lists are intentionally small; sort after the indexed status lookup to avoid a composite-index dependency. */
export async function listApprovedBrandPalettes() { const snapshot = await getAdminDb().collection("brandPalettes").where("status", "==", "active").get(); return snapshot.docs.map((doc) => { const data = doc.data(); return { id: doc.id, name: String(data.name ?? "Approved palette"), background: String(data.background), surface: String(data.surface), primary: String(data.primary), accent: String(data.accent) }; }).sort((left, right) => left.name.localeCompare(right.name)); }
export async function getApprovedBrandPalette(id: string) { const snapshot = await getAdminDb().doc(`brandPalettes/${id}`).get(); if (!snapshot.exists || snapshot.data()?.status !== "active") return null; const data = snapshot.data()!; return { id: snapshot.id, name: String(data.name ?? "Approved palette"), background: String(data.background), surface: String(data.surface), primary: String(data.primary), accent: String(data.accent) } satisfies BrandPalette; }
export async function createBrandPalette(actorUid: string, raw: unknown) { const input = brandPaletteSchema.parse(raw); const palette: BrandPalette = { id: input.operationId, name: input.name, background: input.background, surface: input.surface, primary: input.primary, accent: input.accent }; paletteVariables(palette); const db = getAdminDb(); await db.runTransaction(async (transaction) => { const ref = db.doc(`brandPalettes/${palette.id}`); if ((await transaction.get(ref)).exists) return; transaction.set(ref, { ...palette, status: "active", createdAt: FieldValue.serverTimestamp(), createdBy: actorUid }); transaction.set(db.doc(`platformAuditEvents/${randomUUID()}`), { action: "brand_palette.created", actorUid, paletteId: palette.id, createdAt: FieldValue.serverTimestamp(), result: "success" }); }); return palette; }
