export const themeIds = ["nature-minimal", "warm-elegant", "dark-modern", "soft-pastel"] as const;
export type ThemeId = (typeof themeIds)[number];

export type StudioTheme = { id: ThemeId; name: string; description: string; background: string; surface: string; surfaceSecondary: string; primary: string; primaryHover: string; secondary: string; accent: string; text: string; textMuted: string; border: string; success: string; warning: string; danger: string; inputBackground: string; inputBorder: string; buttonBackground: string; buttonText: string; buttonHover: string; navigationBackground: string; navigationText: string; navigationActive: string; navigationActiveBackground: string; skeletonBackground: string; skeletonHighlight: string; focusRing: string };

export const studioThemes: Record<ThemeId, StudioTheme> = {
  "nature-minimal": { id: "nature-minimal", name: "Nature Minimal", description: "Calm sage, deep green, and soft cream.", background: "#F7F3EA", surface: "#FCFAF5", surfaceSecondary: "#C7D8CE", primary: "#163C35", primaryHover: "#102F2A", secondary: "#8FAF9F", accent: "#C7D8CE", text: "#18332E", textMuted: "#55736A", border: "#C7D8CE", success: "#2F7A57", warning: "#9A6A19", danger: "#A6443C", inputBackground: "#FCFAF5", inputBorder: "#A9C1B5", buttonBackground: "#163C35", buttonText: "#FCFAF5", buttonHover: "#102F2A", navigationBackground: "#FCFAF5", navigationText: "#18332E", navigationActive: "#163C35", navigationActiveBackground: "#E3EEE7", skeletonBackground: "#DCE9E1", skeletonHighlight: "#F4F8F5", focusRing: "#8FAF9F" },
  "warm-elegant": { id: "warm-elegant", name: "Warm Elegant", description: "Boutique warmth in terracotta, sand, and ivory.", background: "#F6ECE3", surface: "#FCF8F5", surfaceSecondary: "#E9D2BC", primary: "#6A2E12", primaryHover: "#4D200C", secondary: "#C98964", accent: "#E9D2BC", text: "#6A2E12", textMuted: "#A85F38", border: "#E9D2BC", success: "#4B7E61", warning: "#9A661F", danger: "#A83E32", inputBackground: "#FCF8F5", inputBorder: "#E9D2BC", buttonBackground: "#6A2E12", buttonText: "#FCF8F5", buttonHover: "#4D200C", navigationBackground: "#FCF8F5", navigationText: "#6A2E12", navigationActive: "#6A2E12", navigationActiveBackground: "#F1E1D1", skeletonBackground: "#E9D2BC", skeletonHighlight: "#F9F1EB", focusRing: "#C98964" },
  "dark-modern": { id: "dark-modern", name: "Dark Modern", description: "High-contrast charcoal with a deep green edge.", background: "#101714", surface: "#1B2722", surfaceSecondary: "#293A33", primary: "#A8D5BE", primaryHover: "#D1EADB", secondary: "#6C9983", accent: "#355143", text: "#F5F8F4", textMuted: "#BDD0C4", border: "#466354", success: "#86D5A8", warning: "#F0C56A", danger: "#FF968B", inputBackground: "#17211D", inputBorder: "#587866", buttonBackground: "#A8D5BE", buttonText: "#102019", buttonHover: "#D1EADB", navigationBackground: "#17211D", navigationText: "#E9F2EC", navigationActive: "#D1EADB", navigationActiveBackground: "#294638", skeletonBackground: "#2A3B33", skeletonHighlight: "#40564A", focusRing: "#D1EADB" },
  "soft-pastel": { id: "soft-pastel", name: "Soft Pastel", description: "Fresh lilac, blush, and pale blue with calm contrast.", background: "#F6F2FA", surface: "#FFFDFE", surfaceSecondary: "#E8E0F3", primary: "#493965", primaryHover: "#35264D", secondary: "#9C82B5", accent: "#DCE8F5", text: "#352C45", textMuted: "#756887", border: "#D8CDE8", success: "#397B66", warning: "#956A1A", danger: "#A8475A", inputBackground: "#FFFDFE", inputBorder: "#D8CDE8", buttonBackground: "#493965", buttonText: "#FFFDFE", buttonHover: "#35264D", navigationBackground: "#FFFDFE", navigationText: "#352C45", navigationActive: "#493965", navigationActiveBackground: "#EEE7F6", skeletonBackground: "#E9E1F1", skeletonHighlight: "#FAF7FC", focusRing: "#9C82B5" },
};

export function resolveTheme(value: unknown): ThemeId { return typeof value === "string" && themeIds.includes(value as ThemeId) ? value as ThemeId : "nature-minimal"; }
